input {
    gelf {
        port => 12201
    }
}
output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        user => "elastic"
        password => "changeme"
        index => "logstash-%{+YYYY-MM-dd}"
    } 
}

filter {
  if [level] == "debug" {
    drop { }
  }
   throttle {
    before_count => 5
    after_count => 1
    period => 60
    key => "%{host}"
  }
}

