services:
  nginx:
    container_name: nginx-lb
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - front-spa:/var/www/html
    depends_on:
      - frontend
      # - auth-service
      # - game-service
    networks:
      - transcendence-network

  frontend:
    container_name: frontend-spa
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - front-spa:/usr/src/app/
    networks:
      - transcendence-network

  # auth-service:
  #   container_name: auth-service
  #   build:
  #     context: ./auth-service
  #     dockerfile: Dockerfile
  #   volumes:
  #     - auth-db:/data   # SQLite DB
  #   networks:
  #     - transcendence-network

  # game-service:
  #   container_name: game-service
  #   build:
  #     context: ./game-service
  #     dockerfile: Dockerfile
  #   volumes:
  #     - game-data-db:/data    # SQLite
  #   networks:
  #     - transcendence-network

  # Other services here


volumes:
  front-spa:
    driver: local
    driver_opts:
      type: none
      device: /home/nerea/Documents/transcendence-pvc/front-spa
      o: bind
  # auth-db:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/nerea/Documents/transcendence-pvc/auth-db
  # game-data-db:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/nerea/Documents/transcendence-pvc/game-data-db
  

networks:
  transcendence-network:
    driver: bridge
