services:
  nginx:
    container_name: nginx-lb
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "8080:443"
    volumes:
      - front-spa:/var/www/html
    depends_on:
      - frontend
      - auth-service
      - game-service
      - users-service
      - stats-service
      - rabbitmq
    networks:
      - transcendence-network
    profiles: ["app"]
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "transcendence"

  frontend:
    container_name: frontend-spa
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - front-spa:/usr/src/app/
    networks:
      - transcendence-network
    profiles: ["app"]

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - .env 
    volumes:
      - auth-db:/data/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - transcendence-network
    profiles: ["app"]

  stats-service:
    container_name: stats-service
    build:
      context: ./stats-service
      dockerfile: Dockerfile
    env_file:
      - .env 
    volumes:
      - stats-db:/data/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - transcendence-network
    profiles: ["app"]
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "transcendence"

  game-service:
    container_name: game-service
    build:
      context: ./backend/game
      dockerfile: Dockerfile
    volumes:
      - game-data-db:/data
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - transcendence-network
    profiles: ["app"]
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "transcendence"

  users-service:
    container_name: users-service
    build:
      context: ./users-service
      dockerfile: Dockerfile
    volumes:
      - users-db:/data/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - transcendence-network
    env_file:
      - .env
    profiles: ["app"]
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "transcendence"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - transcendence-network
    env_file:
      - .env
    profiles: ["app"]
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"] 
      interval: 10s 
      retries: 5
      start_period: 30s
      timeout: 5s
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "transcendence"

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.28
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./monitoring/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.ml.enabled=false
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - transcendence-network
    profiles: ["elk"]
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:$ELASTIC_PASSWORD", "-f", "http://localhost:9200"]
      interval: 15s
      timeout: 10s
      retries: 5
    mem_limit: 1gb

  logstash:
    container_name: logstash
    image: logstash:7.17.28
    volumes:
      - ./monitoring/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./monitoring/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 12201:12201/udp
    networks:
      - transcendence-network
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    profiles: ["elk"]

  kibana:
    container_name: kibana
    image: kibana:7.17.28
    volumes:
      - ./monitoring/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana:/usr/share/kibana/data
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    networks:
      - transcendence-network
    environment:
      - NODE_OPTIONS=--max-old-space-size=768
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    profiles: ["elk"]

volumes:
  front-spa:
  auth-db:
  game-data-db:
  users-db:
  stats-db:
  elasticsearch:
  logstash:
  kibana:
  rabbitmq-data:

networks:
  transcendence-network:
    driver: bridge
