worker_processes auto;

events {
    worker_connections 1024;
}


http {

	access_log /dev/stdout;
    error_log /dev/stderr warn;

	include /etc/nginx/mime.types;
    sendfile on;

	# upstream	auth-service {
	# 	server auth-service:80;
	# }

	# upstream	game-service {
	# 	server	game-service:80;
	# }

	server {
		listen			80;
		server_name	ft_transcendence.com;

		# Redirect HTTP to HTTPS
		return 301 https://$host$request$uri;
	}

	server {
		listen 443	ssl;
		server_name	ft_transcendence.com;

		ssl_certificate		/etc/ssl/nginx.crt;
		ssl_certificate_key	/etc/ssl/private/nginx.key;
		ssl_protocols		TLSv1.2 TLSv1.3;

		# Reverse proxy for frontend
		# location / {
		# 	proxy_pass	http://frontend;
			
		# 	proxy_set_header	Host $host;
		# 	proxy_set_header	X-Real-IP	$remote_addr;
		# 	proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
		# 	proxy_set_header X-Forwarded-Proto $scheme;
		# }

		
		location / {
			index index.html;
			root /usr/share/nginx/html/src;
			try_files $uri $uri/ /index.html; 
    	}

	# 	# Reverse proxy for /api/auth/
	# 	location /api/auth/ {
	# 			proxy_pass http://auth_service;  # Proxy to the backend API - Auth
				
	# 			proxy_set_header Host $host;
	# 			proxy_set_header X-Real-IP $remote_addr;
	# 			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	# 			proxy_set_header X-Forwarded-Proto $scheme;
	# 	}

	# 	# Reverse proxy for /api/game/
	# 	location /api/game/ {
	# 			proxy_pass http://game_service;  # Proxy to the backend API - Game
				
	# 			proxy_set_header Host $host;
	# 			proxy_set_header X-Real-IP $remote_addr;
	# 			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	# 			proxy_set_header X-Forwarded-Proto $scheme;
	# 	}
	# }
	}
}
